apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: iris-green-example-secret
  namespace: iris-green-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-wide-store

  target:
    name: iris-green-example-secret
    creationPolicy: Owner

  data:
  # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
  - secretKey: example
    remoteRef:
      key: iris-green-example-secret